config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "items#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # The user will need to see the bookings of his items, this route will provide with the correct path.
  get "my_bookings" => "bookings#my_bookings"
  # The user will need to see the items that he has rented from other people, this route will provide the user with the correct path.
  get "my_rented_items" => "bookings#my_rented_items"

  resources :items, only: %i[new create index show edit update] do
    resources :bookings, only: %i[new create]
  end

  resources :bookings, only: %i[edit update]
  get "requests", to: "bookings#requests"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :item
  validate :item_not_owned_by_user
  validates :status, presence: true
  validates :booking_date, presence: true
  validates :return_date, presence: true

  private

  def item_not_owned_by_user
    if item.present? && item.user == user
      errors.add(:item, "You cannot book your own item.")
    end
  end
end

# Make a method belongs to current-user -> posted-items -> posted items that are booked.

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # [...]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number, :avatar ])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone_number, :avatar])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_item, only: %i[new create]
  before_action :set_booking, only: %i[edit update]

  def my_bookings
    @bookings = Booking.where(user: current_user)
  end

  def my_rented_items
    @items = current_user.items
    @booking = Booking.where(item: params[:item_id])
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.item = @item

    if @booking.save
      redirect_to root_path, notice: "Booking request submitted!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @booking.update(booking_params)
    redirect_to requests_path
  end

  def requests
    bookings = Booking.all
    @bookings = bookings.joins(:item).where(items: { user: current_user })
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_item
    @item = Item.find(params[:item_id])
  end

  def booking_params
    params.require(:booking).permit(:status, :item_id, :booking_date, :return_date)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
    @booking = Booking.find_by(user: current_user, item: @item)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user

    if @item.save
      redirect_to item_path(@item), notice: 'Item was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to item_path(item)
  end

  private

  def item_params
    params.require(:item).permit(:title, :description, :price, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<div class="container">
  <div class="card-top-container">
    <h2><%= @booking.user.first_name %> <%= @booking.user.last_name %> wants to book <%= @booking.item.title %></h2>
  </div>
  <div class="form-container">
    <%= simple_form_for [@item, @booking], html: { class: "custom-form" } do |f| %>
      <%= f.input :status, :collection => %w[Approved Rejected] %>
      <%= f.button :submit, "Submit Booking" %>
    <% end %>
  </div>
</div>

app/views/bookings/my_bookings.html.erb
<%# My bookings page needs to associate with each unique user. Use the user id %>

<%# It is not a page to see all the posted items of the user,
just the items that were booked from other people. %>

<%#   %>
<div class="banner">
  <div class="container">
    <h1>My bookings</h1>
    <p>List of items you've requested to book from others.</p>
  </div>
</div>


<div class="container d-flex flex-wrap justify-content-center align-items-center">
  <% @bookings.each do |booking| %>
    <div class="card-container">
      <div class="card-title-section">
        <div class="card-title-section-col-l">
          <p><%= booking.item.title %></p>
          <p>Renting date</p>
          <%= booking.booking_date %>
        </div>
        <div class="card-title-section-col-r">
          <p class="btn-status"><%= booking.status %></p>
          <p>Return date</p>
          <%= booking.return_date %>
        </div>
      </div>
      <div class="d-flex justify-content-center align-items-center">
        <%= image_tag(booking.item.photo.attached? ? cl_image_path(booking.item.photo.key) : asset_path('default_no_image.jpg')) %>
      </div>
      <div class="card-infos-section">
        <p class="card-txt-price">$<%= booking.item.price %></p>
        <p class="text single-line"><%= booking.item.description %></p>
      </div>
      <div class="card-btn-details">
        <%= link_to 'More Details', item_path(booking.item), class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/bookings/my_rented_items.html.erb
<div class="banner">
  <div class="container">
    <h1>My items</h1>
    <p>List of items I’m currently offering out to others.</p>
  </div>
</div>

<div class="container d-flex flex-wrap justify-content-center align-items-center">
  <% @items.each do |item| %>
    <div class="card-container">
      <div class="card-title-section">
        <div class="card-title-section-col-l">
          <p><%= item.title %></p>
        </div>
      </div>
      <div class="d-flex justify-content-center align-items-center">
        <%= image_tag(item.photo.attached? ? cl_image_path(item.photo.key) : asset_path('default_no_image.jpg')) %>
      </div>
      <div class="card-infos-section">
        <p class="card-txt-price">$<%= item.price %></p>
        <p class="text single-line"><%= item.description %></p>
      </div>
      <div class="card-btn-details">
        <%= link_to 'Edit', edit_item_path(item), class: "btn btn-primary" %>

      </div>
    </div>
  <% end %>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <div class="card-top-container">
    <h2>Request to book</h2>
  </div>

  <%= simple_form_for [@item, @booking], html: { class: "custom-form" } do |f| %>
    <div class="custom-date-field">
      <div class="form-row">
        <div class="date-part">
          <%= f.input :booking_date, as: :date, label: "Booking Date" %>
        </div>
      </div>

      <div class="form-row">
        <div class="date-part">
          <%= f.input :return_date, as: :date, label: "Return Date" %>
        </div>
      </div>
      <%= f.button :submit, "Submit Booking",class: "custom-button" %>
    </div>
  <% end %>
</div>

app/views/bookings/requests.html.erb
<div class="container">
  <h1 class="mt-5">Pending requests...</h1>
  <% @bookings.each do |booking| %>
    <div class="notification">

      <%= image_tag("default_avatar.png", class: "avatar-large") %>
      <div class="notification-content">
        <p><small><%= booking.user.first_name %></small></p>
        <p>Wants to book your item: <%= booking.item.title %></p>
      </div>

      <% if booking.status == "pending" %>
        <div class="notification-actions">
          <%= link_to edit_booking_path(booking), class: "text-decoration-none" do %>
            Edit <i class="fas fa-pencil-alt"></i>
          <% end %>
        </div>
      <% else %>
        <div class="d-flex justify-content-end">
          <%= booking.status %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/items/edit.html.erb
<div class="container">
  <div class="card-top-container">
    <h1>Editing <%= @item.title %></h1>
  </div>
  <div class="form-container">
    <%= simple_form_for(@item) do |f| %>
      <%= f.input :title, input_html: { class: "form-input" } %>
      <%= f.input :description, as: :text, input_html: { class: 'form-input' } %>
      <div class="form-group">
        <%= f.input :photo, as: :file %>
    </div>
      <%= f.input :price, as: :integer, input_html: { min: 0, step: 1, class: "form-input" } %>

      <%= f.submit "Confirm changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/items/index.html.erb
<div class="banner">
  <div class="container">
    <h1>Welcome to Lowballs</h1>
    <p>Browse board games available for rent.</p>
  </div>
</div>
<div class="container d-flex flex-wrap justify-content-center align-items-center">
  <% @items.each do |item| %>
    <div class="card-container">
      <div class="card-title-section">
        <div class="card-title-section-col-l"><%= item.title %></div>
      </div>
      <div class="d-flex justify-content-center align-items-center">
        <%= image_tag(item.photo.attached? ? cl_image_path(item.photo.key) : asset_path('https://res.cloudinary.com/diwuyv3c8/image/upload/v1732910542/d11b8dea-8c12-44df-92fc-057e426b5b61.png')) %>
      </div>
      <div class="card-infos-section">
        <p class="card-txt-price">$<%= item.price %></p>
        <p class="text single-line"><%= item.description %></p>
      </div>
      <div class="card-btn-details">
        <%= link_to 'More Details', item_path(item), class: "card-button" %>
      </div>
    </div>
  <% end %>
</div>

app/views/items/new.html.erb
<div class="container">
  <div class="card-top-container">
    <h2>Add a new item</h2>
  </div>
  <div class="form-container">
    <%= simple_form_for(@item) do |f| %>
      <%= f.input :title, input_html: { class: "form-input" } %>
      <%= f.input :description, as: :text, input_html: { class: 'form-input' } %>
      <div class="form-group">
        <%= f.input :photo, as: :file %>
    </div>
      <%= f.input :price, as: :integer, input_html: { min: 0, step: 1, class: "form-input" } %>

      <%= f.submit "Add Item", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/items/show.html.erb
<div class="container">
  <div class="card-top-container">
    <h2>Home / <%= @item.title %> details page</h2>
  </div>

  <div class="card-info-product">
      <div class="card-title-section">
        <div class="card-title-section-col-l"><%= @item.title %></div>
      </div>
      <div class="card-img test">
        <%= image_tag(@item.photo.attached? ? cl_image_path(@item.photo.key) : asset_path('default_no_image.jpg')) %>
      </div>
      <div class="card-infos-section">
        <div class="card-txt-price">$<%= @item.price %></div>
        <div class="card-contact">
          <h3>Contact</h3>
          <div><i class="fa-solid fa-user-tie"></i> <%= @item.user.first_name %> <%= @item.user.last_name %></div>
          <% if !(@item.user.phone_number.empty?) %>
          <div><i class="fa-solid fa-phone"></i> <%= @item.user.phone_number %></div>
          <% end %>
        </div>
        <div class="card-item-description">
          <h3>Description</h3>
          <p class="text single-line"><%= @item.description %></p>
        </div>
      </div>
      <div class="card-btn-details">
        <% unless @item.user == current_user%>
          <% if @booking%>
          <%= link_to 'Pending...', new_item_booking_path(@item), class: "btn btn-primary disabled" %>
          <% else %>
            <%= link_to 'Book item', new_item_booking_path(@item), class: "btn btn-primary" %>
          <% end %>
        <% end %>
      </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lowballs</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  <style>
@import url('https://fonts.googleapis.com/css2?family=Nunito+Sans:ital,opsz,wght@0,6..12,200..1000;1,6..12,200..1000&display=swap');
</style>
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">

  </head>

  <body>
    <div class="wrapper">
      <header>
        <%= render "shared/navbar" %>
        <%= render "shared/flashes" %>
      </header>
      <main>
        <%= yield %>
      </main>
      <footer>
        <%= render "shared/footer" %>
      </footer>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="f-c">
    ©copyright, Le Wagon Batch#1851, A.Gabriel, B.M.Raphaël, D.Anabelle, S.J.Jelani
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to items_path, class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/diwuyv3c8/image/upload/v1732902047/lb_logo_j3tvua.svg" %>

    <% end %>



    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>




    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav me-auto">

      <!-- Dropdown for "Renter" -->
      <li class="nav-item dropdown">
      <i class="bi bi-chevron-down"></i>
        <% if user_signed_in? %>
                <li class="nav-item dropdown">

        <%= link_to "Renter", my_rented_items_path, class: "nav-link dropdown-toggle", data: { bs_toggle: "dropdown" }, aria: { haspopup: "true", expanded: "false" } %>
        <ul class="dropdown-menu dropdown-menu-end">
          <li>
            <%= link_to "My Items", my_rented_items_path, class: "dropdown-item" %>
          </li>
          <li>
            <%= link_to "My Bookings", my_bookings_path, class: "dropdown-item" %>
          </li>
        </ul>
      </li>

      </li>
      <!-- Dropdown for "Lender" -->

      <li class="nav-item dropdown">
        <%= link_to "Lender", my_bookings_path, class: "nav-link dropdown-toggle", data: { bs_toggle: "dropdown" }, aria: { haspopup: "true", expanded: "false" } %>
        <ul class="dropdown-menu dropdown-menu-end">
          <li>
            <%= link_to "Pending Requests", requests_path, class: "dropdown-item" %>
          </li>
          <li>
            <%= link_to "List new items", new_item_path, class: "dropdown-item" %>
          </li>
        </ul>
      </li>


          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
            <%#= cl_image_tag current_user.avatar.key, class: "avatar" %>
            <%#= image_tag(current_user.avatar.attached? ? cl_image_path(current_user.avatar.key, class: "avatar") : asset_path('default_avatar.png', class: "avatar")) %>
            <%# if current_user.avatar.attached? %>
              <%#cl_image_tag current_user.avatar.key, class: "avatar" %>
            <%# else %>
              <%# image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
            <%# end %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <p class= "dropdown-item"><%= current_user.first_name %> <%= current_user.last_name %></p>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>




           <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>

      </ul>
        <% end %>

    </div>
  </div>
</div>